In [8]:
import numpy as np
a=[[30,40,50],[60,70,80]]
arr= np.array(a)
print(arr)
# functions:-
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(arr.dtype) #data type of array
print(arr.astype(str)) #can convert float to int but not strung to int or float

[[30 40 50]
 [60 70 80]]
(2, 3)
2
6
int64
[['30' '40' '50']
 ['60' '70' '80']]


In [3]:
import  numpy as np

arr1=np.array([[30,40],[60,70]])
arr2=np.array([[80,50],[60,90]])
print(arr1+arr2)
print(np.add(arr1,arr2)) #we can also do this also , to find the calculation.




[[110  90]
 [120 160]]
[[110  90]
 [120 160]]


In [4]:
import  numpy as np

arr1=np.array([[30,40],[60,70]])
arr2=np.array([[80,50],[60,90]])
print(arr1*arr2)
print(np.multiply(arr1,arr2)) #we can also do this also , to find the calculation.


[[2400 2000]
 [3600 6300]]
[[2400 2000]
 [3600 6300]]


In [5]:
arr1=np.array([3,4,5,6])
arr2=np.array([3])
print(np.power(arr1,arr2))

[ 27  64 125 216]
