In [32]:
# Aggregate functions in numpy

import numpy as np

a=np.array([20,40,60,70])
print (np.sum(a))
print (np.min(a))
print (np.max(a))
print (np.size(a))
print (np.mean(a))
print (np.cumsum(a)) #adding each element and writing it consecutively (cumulative sum)
print (np.cumprod(a))




190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [28]:
a=[100,150,199,200,250,130]
b=[10,50,30,40,30,10]

price= np.array(a)
quantity=np.array(b)

# print(price,quantity)
print(price,"\n",quantity)
print()


c=np.cumprod([price,quantity],axis=0) #price*quantity
# print(c)
print((c[1]).sum())


# c=np.cumprod([price,quantity],axis=1) #price*quantity
# print(c)








[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

31270
