In [1]:
a=[30,40,50]
b=[5,5,3]
print(a+b)

[30, 40, 50, 5, 5, 3]


In [14]:
# concatenate

import numpy as np
arr1 = np.array([[30,40],[56,50]])
arr2 = np.array([[5,5],[2,3]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [56 50]
 [ 5  5]
 [ 2  3]]


In [18]:
print(np.concatenate([arr1,arr2],axis = 0)) #0=1-d dimension and 1= 2-d dimension
# axis=1 for  horizontal concatenation and axis=0 for vertical concatenation

[[30 40]
 [56 50]
 [ 5  5]
 [ 2  3]]


In [16]:
print(np.hstack([arr1,arr2])) # horizontal concatenation

[[30 40  5  5]
 [56 50  2  3]]


In [17]:
print(np.vstack([arr1,arr2]))  # vertical concatenation

[[30 40]
 [56 50]
 [ 5  5]
 [ 2  3]]


In [30]:
a= np.array([20,30,40,50,43])
print(np.array_split(a,4))  # a,4 means 4 part me split hoga


[array([20, 30]), array([40]), array([50]), array([43])]


In [67]:
a= np.array([20,30,40,56,50,43])
b=np.array_split(a,3)
print(b[1])

[40 56]


In [71]:

c= np.array([[20,30,40],[56,50,43]])
print(np.array_split(c,4))


[array([[20, 30, 40]]), array([[56, 50, 43]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]


In [104]:
import numpy as np

arr1 = np.array([[30,40],[56,50]])
# print(np.append(a,90))
# print(np.append(a,[90,100]))



[20 30 40 56 50 43 90]


In [94]:
# print(np.insert(a,1,50))
print(np.insert(a,1,[50,60],axis = 0))
print(np.insert(a,1,[50],axis = 0))   

[20 50 60 30 40 56 50 43]
[20 50 30 40 56 50 43]


In [98]:
# print(np.insert(c,1,50))
print(np.insert(c,1,[50,60],axis = 1))
print(np.insert(c,[1,2],[50],axis = 0))


[[20 50 30 40]
 [56 60 50 43]]
[[20 30 40]
 [50 50 50]
 [56 50 43]
 [50 50 50]]


In [109]:
# n=np.array([[20,4,5],[62,569,5]])
print(np.delete(a,1))
# print(np.delete(c,1,axis=1))

[20 40 56 50 43]
