In [19]:
import numpy as np
# creating arrays:-
arr= np.array([[10,20,30,40],[50,60,70,80],[50,60,70,80]])
print(arr)
print(type(arr))

[[10 20 30 40]
 [50 60 70 80]
 [50 60 70 80]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
# slicing:-
arr= np.array([[10,20,30,40],[50,60,70,80],[50,60,70,80]])
# for single elements set
# print(arr[0:3])
# print(arr[0:])
# print(arr[3:])
# print(arr[2:])
# print(arr[:3])

# for two elements set
# print(arr[0:2,0:]) 
# its output will be of 4 elements of both set , because it will have to show equal 
# number of elements in both the set.
# if I want index 1 elements and index 2 elements:
# print(arr[0,1:3]) 
# print(arr[1,2:4]) 
# print(arr[2,2]) 








[20 30]
[70 80]
70


In [21]:
import numpy as np
# attributes of array:
arr= np.array([[10,20,30,40],[50,60,70,80],[50,60,70,80]])
print(np.shape(arr))
# output is - (3, 4) , it means 3 rows and 4 columns 
print(np.size(arr))
# output is - 12
print(np.ndim(arr))
# output is - 2 , i.e rows and columns
print (arr.dtype)
# output is - int64


(3, 4)
12
2
int64
