In [1]:
import numpy as np

# ar=np.array([4,5,2,7,8,3,5])
# print(np.sort(ar))


[2 3 4 5 5 7 8]


In [3]:
# ar=np.array([[4,5,2,7,8,3,5],[3,4,2,6,8,5,7]])
# print(np.sort(ar))

[[2 3 4 5 5 7 8]
 [2 3 4 5 6 7 8]]


In [19]:
ar=np.array([4,5,2,7])
# s= np.where(ar == 4)
s= np.where(ar % 2==0)
print(s)

4


In [27]:
# searchsorted -- array must be sorted

ar=np.array([2,3,4,9,10])
ss= np.searchsorted(ar,9)
print(ss)


3


In [29]:
# filter

import numpy as np
ar=np.array([2,3,4,5])
# -- finding the even number - method-1
# fa=[True, False,True,False] 
fa=[True, False,False,False]

new= ar[fa]
print(new)

[2]


In [32]:
# -- finding the even number - method-2

ar=np.array([2,3,40,5])
# fa= ar>35
fa= ar%2==0
new=ar[fa]
print(new)

[ 2 40]
